[project]
name = "xarray-graph"
version = "0.0.0"
description = "PyQt UIs for Xarray DataTree including tree view and DataArray slice graphing and processing."
authors = [
    {name = "Marcel Goldschen-Ohm", email = "goldschen-ohm@utexas.edu"},
]
readme = "README.md"
keywords = ["xarray", "DataTree", "tree", "PyQt", "PySide", "pyqtgraph", "graph", "plot", "signal processing", "n-dimensional"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: User Interfaces",
]
requires-python = ">=3.12"
dependencies = [
    "xarray",
    "h5netcdf",
    "zarr",
    "scipy",
    "pint",
    "lmfit",
    "QtPy",
    "QtAwesome",
    "pyqtgraph",
    "qtconsole",
    "cmap",
    "requests",
    "cftime",
]

[project.optional-dependencies]
qt = [
    "PySide6 >=6.2.2,!=6.9.1",
]

[project.urls]
homepage = "https://github.com/marcel-goldschen-ohm/xarray-graph"
repository = "https://github.com/marcel-goldschen-ohm/xarray-graph"
issues = "https://github.com/marcel-goldschen-ohm/xarray-graph/issues"

[project.scripts]
xarray-graph = "xarray_graph.__main__:xgraph"
xarray-tree = "xarray_graph.__main__:xtree"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
