from xarray_graph.widgets.CollapsibleSectionsSplitter import CollapsibleSectionsSplitter
from xarray_graph.widgets.ColorButton import ColorButton
from xarray_graph.widgets.MultiValueSpinBox import MultiValueSpinBox
from xarray_graph.widgets.TableWidgetWithCopyPaste import TableWidgetWithCopyPaste
