name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Upload release to PyPI
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Get latest release tag
      id: get_tag
      run: |
        # Fetch the latest release tag name and save it to the output
        LATEST_TAG=$(gh release view --json tagName --template '{{.tagName}}')
        echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check tag
      run: echo "The latest release tag is ${{ steps.get_tag.outputs.tag }}"
    
    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.12.1" # uv version
        python-version: "3.13"

    - name: Set project version to tag
      run: uv version ${{ steps.get_tag.outputs.tag }}

    - name: Check project version
      run: uv version
    
    - name: Install the project
      run: uv sync
    
    - name: Build package
      run: uv build
    
    - name: Publish package to PyPI
      run: uv publish
